name: Send email


inputs:
  username:
    required: true
  password:
    required: true
  to:
    required: true
  subject:
    required: true
  message:
    required: true
    
env:
  secret: ${{ secrets.token }}
  
runs:
  using: 'composite'
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: thalissonOrg/email
          ref: main

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
        shell: bash
          

      - name: execute py script
        env:
          EMAIL_USERNAME: ${{ inputs.username }}
          EMAIL_PASSWORD: ${{ inputs.password }}
          TO_EMAIL: ${{ inputs.to }}
          SUBJECT: ${{ inputs.message }}
          MESSAGE: ${{ inputs.subject }}
        run: |
          python -c "
          import smtplib
          import os
          import email.message

          from_email = os.environ.get('EMAIL_USERNAME')
          password = os.environ.get('EMAIL_PASSWORD')
          to_email = os.environ.get('TO_EMAIL')
          message = os.environ.get('MESSAGE')
          subject = os.environ.get('SUBJECT')

          msg = email.message.Message()
          msg.set_payload(subject)
          msg['Subject'] = message

          server = smtplib.SMTP('smtp.gmail.com', 587)
          server.ehlo()
          server.starttls()
          server.ehlo()
          server.login(from_email, password)
          server.sendmail(from_email, to_email, msg.as_string())
          server.rset()
          server.quit()
          "
        shell: bash
     
