name: Send email


inputs:
  username:
    required: true
  password:
    required: true
  to:
    required: true
  subject:
    required: true
  message:
    required: true
    
runs:
  using: 'composite'
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: thalissonOrg/email
          ref: main

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
        shell: bash
          

      - name: execute py script
        env:
          EMAIL_USERNAME: ${{ inputs.username }}
          EMAIL_PASSWORD: ${{ inputs.password }}
          TO_EMAIL: ${{ inputs.to }}
          SUBJECT: ${{ inputs.message }}
          MESSAGE: ${{ inputs.subject }}
        run: |
          python -c "
            import smtplib
            import os
            from email.mime.text import MIMEText
            from email.mime.multipart import MIMEMultipart
            
            from_email = os.environ.get('EMAIL_USERNAME')
            password = os.environ.get('EMAIL_PASSWORD')
            to_email = os.environ.get('TO_EMAIL')
            html_message = os.environ.get('HTML_MESSAGE')
            subject = os.environ.get('SUBJECT')
            
            # Create a multipart message
            msg = MIMEMultipart()
            msg['From'] = from_email
            msg['To'] = to_email
            msg['Subject'] = subject
            
            # Create a plain text alternative part (optional, for email clients that can't display HTML)
            text = "This is a plain text version of the email."
            plain_text_part = MIMEText(text, 'plain')
            msg.attach(plain_text_part)
            
            # Create an HTML alternative part
            html_part = MIMEText(html_message, 'html')
            msg.attach(html_part)
            
            # Connect to the SMTP server
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.ehlo()
            server.starttls()
            server.ehlo()
            
            # Log in and send the email
            server.login(from_email, password)
            server.sendmail(from_email, to_email, msg.as_string())
            server.rset()
            server.quit()
          "
        shell: bash
     
