name: Send email


inputs:
  username:
    required: true
  password:
    required: true
  to:
    required: true
  subject:
    required: true
  message:
    required: true
    
env:
  secret: ${{ secrets.token }}
  
runs:
  using: 'composite'
  steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          repository: thalissonOrg/email
          ref: main

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
        shell: bash
          

      - name: execute py script
        env:
          EMAIL_USERNAME: ${{ inputs.username }}
          EMAIL_PASSWORD: ${{ inputs.password }}
          TO_EMAIL: ${{ inputs.to }}
          SUBJECT: ${{ inputs.message }}
          MESSAGE: ${{ inputs.subject }}
        run: |
          ls -la
          echo $secret
          python mailSender.py
        shell: bash
     
